2017-04-21 10:20:12 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 10:20:23 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 10:20:46 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 10:20:57 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 10:20:57 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 10:20:57 nativedriver.py methed:creatNativeDriver line:42 ERROR - Message: A new session could not be created. (Original error: Requested a new session but one was in progress)

2017-04-21 10:20:57 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: Requested a new session but one was in progress)


2017-04-21 10:20:57 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 10:20:57 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 10:20:57 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 10:21:07 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 10:21:10 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 10:21:11 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 10:21:11 nativedriver.py methed:closeNativedriver line:52 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 10:21:11 nativedriver.py methed:closeNativedriver line:53 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 48, in closeNativedriver
    __global_nativedriver.close_app()
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 10:39:12 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 10:39:12 nativedriver.py methed:creatNativeDriver line:42 ERROR - type object 'Command' has no attribute 'ADB'
2017-04-21 10:39:12 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 89, in __init__
    self.command_executor = RemoteConnection(command_executor, keep_alive=keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 446, in __init__
    ('POST', '/session/$sessionId/adb'),
AttributeError: type object 'Command' has no attribute 'ADB'

2017-04-21 10:39:12 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 10:39:12 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 10:39:12 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 10:49:45 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 10:49:45 nativedriver.py methed:creatNativeDriver line:42 ERROR - type object 'Command' has no attribute 'ADB'
2017-04-21 10:49:45 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 89, in __init__
    self.command_executor = RemoteConnection(command_executor, keep_alive=keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 446, in __init__
    ('POST', '/session/$sessionId/adb'),
AttributeError: type object 'Command' has no attribute 'ADB'

2017-04-21 10:49:45 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 10:49:45 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 10:49:45 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 10:50:39 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 10:50:39 nativedriver.py methed:creatNativeDriver line:42 ERROR - type object 'Command' has no attribute 'ADB'
2017-04-21 10:50:39 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 89, in __init__
    self.command_executor = RemoteConnection(command_executor, keep_alive=keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 446, in __init__
    ('POST', '/session/$sessionId/adb'),
AttributeError: type object 'Command' has no attribute 'ADB'

2017-04-21 10:50:39 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 10:50:39 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 10:50:39 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 10:51:25 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 10:51:25 nativedriver.py methed:creatNativeDriver line:42 ERROR - type object 'Command' has no attribute 'ADB'
2017-04-21 10:51:25 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 89, in __init__
    self.command_executor = RemoteConnection(command_executor, keep_alive=keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 446, in __init__
    ('POST', '/session/$sessionId/adb'),
AttributeError: type object 'Command' has no attribute 'ADB'

2017-04-21 10:51:25 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 10:51:25 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 10:51:25 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 10:56:51 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 10:56:51 nativedriver.py methed:creatNativeDriver line:42 ERROR - type object 'Command' has no attribute 'ADB'
2017-04-21 10:56:51 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 89, in __init__
    self.command_executor = RemoteConnection(command_executor, keep_alive=keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 446, in __init__
    ('POST', '/session/$sessionId/adb'),
AttributeError: type object 'Command' has no attribute 'ADB'

2017-04-21 10:56:51 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 10:56:51 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 10:56:51 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.1-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 11:04:33 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:04:43 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:08:53 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:09:04 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:12:51 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:13:01 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:13:01 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 11:13:03 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:13:13 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:13:35 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:13:46 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:13:46 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:15:50 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:16:01 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:16:01 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 11:16:03 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:16:03 nativedriver.py methed:creatNativeDriver line:42 ERROR - Message: A new session could not be created. (Original error: Requested a new session but one was in progress)

2017-04-21 11:16:03 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: Requested a new session but one was in progress)


2017-04-21 11:16:03 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:16:03 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 11:16:03 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 11:18:26 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:18:27 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-04-21 11:18:28 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-04-21 11:18:28 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:18:53 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:19:04 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:19:04 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 11:19:06 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:19:15 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:19:38 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:19:48 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:19:48 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:24:35 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:24:46 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:24:47 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 11:24:48 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:24:58 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:25:20 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:25:31 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:25:31 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:26:10 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 11:26:12 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 11:26:13 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:26:23 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:26:46 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:26:56 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:26:56 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:26:56 nativedriver.py methed:creatNativeDriver line:42 ERROR - Message: A new session could not be created. (Original error: Requested a new session but one was in progress)

2017-04-21 11:26:56 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: Requested a new session but one was in progress)


2017-04-21 11:26:56 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:26:56 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:26:56 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:26:56 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:27:39 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:27:39 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:27:39 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:28:18 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 11:28:20 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 11:28:22 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:28:32 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:28:55 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:29:06 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:29:06 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:29:06 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:29:06 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:29:47 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 11:29:49 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 11:29:51 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:30:01 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:30:25 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 11:30:27 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 11:30:39 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:30:39 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 11:30:49 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 11:30:49 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:30:49 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:30:49 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:31:40 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:31:40 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:31:40 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 11:31:46 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 11:31:48 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 14:59:08 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 14:59:54 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 15:00:29 nativedriver.py methed:creatNativeDriver line:42 ERROR - [Errno 10054] 
2017-04-21 15:00:29 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "D:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "D:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "D:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "D:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10054] 

2017-04-21 15:00:29 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 15:00:29 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 15:00:29 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 15:00:29 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 15:00:30 remote_connection.py methed:__init__ line:222 INFO - Could not get IP address for host: 127.0.0.1
2017-04-21 15:00:31 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] >

2017-04-21 15:00:31 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:00:45 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 15:00:56 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 15:00:56 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 15:01:08 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:01:08 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:01:18 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:01:21 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 15:01:22 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 15:01:24 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 15:01:34 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 15:01:34 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 15:01:45 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:02:20 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:02:20 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:02:23 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 15:02:25 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 15:08:04 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 15:08:19 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 15:08:19 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 15:08:39 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:08:39 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:08:49 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:08:49 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 15:09:13 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 15:09:13 nativedriver.py methed:creatNativeDriver line:42 ERROR - Message: A new session could not be created. (Original error: Requested a new session but one was in progress)

2017-04-21 15:09:13 nativedriver.py methed:creatNativeDriver line:43 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 39, in creatNativeDriver
    __global_nativedriver=webdriver.Remote(nativeurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: A new session could not be created. (Original error: Requested a new session but one was in progress)


2017-04-21 15:09:13 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 15:09:13 nativedriver.py methed:getNativeDriver line:61 ERROR - global name '_NativeDriver__global_nativedriver' is not defined
2017-04-21 15:09:13 nativedriver.py methed:getNativeDriver line:62 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\nativedriver.py", line 58, in getNativeDriver
    return __global_nativedriver
NameError: global name '_NativeDriver__global_nativedriver' is not defined

2017-04-21 15:09:13 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 15:09:16 luadriver.py methed:creatLuaDriver line:45 ERROR - Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appiumcenter\luadriver.py", line 42, in creatLuaDriver
    __global_luadriver=webdriver.Remote(luaurl, self.capabilities)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\appium\webdriver\webdriver.py", line 36, in __init__
    super(WebDriver, self).__init__(command_executor, desired_capabilities, browser_profile, proxy, keep_alive)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 247, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "D:\Python27\lib\site-packages\rainbow2_python-1.0.0-py2.7.egg\selenium\webdriver\remote\remote_connection.py", line 527, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "D:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "D:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "D:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "D:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "D:\Python27\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "D:\Python27\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "D:\Python27\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "D:\Python27\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "D:\Python27\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 10054] 

2017-04-21 15:09:16 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:09:26 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:09:26 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 15:09:41 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 15:09:51 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 15:09:51 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 15:10:03 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:10:03 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:10:13 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:10:16 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 15:10:17 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
2017-04-21 15:10:19 nativedriver.py methed:creatNativeDriver line:36 INFO - creat nativedriver
2017-04-21 15:10:28 nativedriver.py methed:getNativeDriver line:56 INFO - get nativedriver
2017-04-21 15:10:28 luadriver.py methed:creatLuaDriver line:39 INFO - creat luadriver
2017-04-21 15:10:39 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:11:14 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:11:14 luadriver.py methed:getLuaDriver line:53 INFO - get luadriver
2017-04-21 15:11:29 luadriver.py methed:closeLuadriver line:48 INFO - close luadriver
2017-04-21 15:11:30 nativedriver.py methed:closeNativedriver line:46 INFO - close nativedriver
